# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# See sample at https://levelup.gitconnected.com/deploying-a-node-app-to-aws-elastic-beanstalk-using-github-actions-d64c7e486701

name: Droplet API Node.js CI

env:
  APP_NAME: Droplet-Environment
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-${GITHUB_SHA}

on:
  push:
    branches: [ master, staging ]

jobs:
  configure_vm:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the VM
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo apt update
            sudo apt-get update
            sudo apt-get install -y python3=3.7.3-1 python3-dbg=3.7.3-1 python3-pip=18.1-5
            sudo pip3 install -U pip
            sudo apt-get update
            sudo apt-get install -y git=1:2.20.1-2+deb10u3 nginx=1.14.2-2+deb10u3 lame=3.100-2+b1 ffmpeg=7:4.1.6-1~deb10u1
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs=14.17.0-1nodesource1

            sudo npm install --global yarn

            yarn production:prep:install
            yarn install
            yarn production
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PUBLIC_KEY }}
