# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# See sample at https://levelup.gitconnected.com/deploying-a-node-app-to-aws-elastic-beanstalk-using-github-actions-d64c7e486701

name: Droplet DropService API Node.js CI

on:
  push:
    branches: [ master, staging ]

jobs:
  # run_test:
  #   runs-on: ubuntu-18.04
  #   if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkoutv2
      
  #     - name: Run tests
  #       run: npm run test

  deploy_master:
    runs-on: ubuntu-18.04
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      SERVER_IP: ${{ secrets.SERVER_IP_MASTER }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME_MASTER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_MASTER }}
    steps:
      - name: Testing runs
        run: echo ${GITHUB_REF_SHA}
          
      - name: SSH into the VM
        uses: fifsky/ssh-action@master
        if: ${{ success() }}
        with:
          # VM is Ubuntu 18.04
          command: |
            test ! -e ~/drop-service && mkdir ~/drop-service
            cd ~/drop-service
            sudo apt update
            sudo apt-get update

            sudo apt-get install -y python3.6=3.6.9-1~18.04ubuntu1.4 python3-pip=9.0.1-2.3~ubuntu1.18.04.4
            sudo pip3 install -U pip==21.1.2

            sudo apt-get install -y git=1:2.17.1-1ubuntu0.8 nginx=1.14.0-0ubuntu1.9 lame=3.100-2 ffmpeg=7:3.4.8-0ubuntu0.2
            curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
            sudo apt-get -y install nodejs=14.17.0-1nodesource1

            npm install --global yarn

            yarn production:prep:install
            yarn install
            yarn production
          host: ${{ env.SERVER_IP }}
          user: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}

  deploy_staging:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/staging' }}
    env: 
      SERVER_IP: ${{ secrets.SERVER_IP_STAGING }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME_STAGING }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
    steps:
      - name: Testing runs
        run: echo ${GITHUB_REF_SHA}
          
      - name: SSH into the VM
        uses: fifsky/ssh-action@master
        if: ${{ success() }}
        with:
          # VM is Ubuntu 18.04
          command: |
            test ! -e ~/drop-service && mkdir ~/drop-service
            cd ~/drop-service
            sudo apt update
            sudo apt-get update

            sudo apt-get install -y python3.6=3.6.9-1~18.04ubuntu1.4 python3-pip=9.0.1-2.3~ubuntu1.18.04.4
            sudo pip3 install -U pip==21.1.2

            sudo apt-get install -y git=1:2.17.1-1ubuntu0.8 nginx=1.14.0-0ubuntu1.9 lame=3.100-2 ffmpeg=7:3.4.8-0ubuntu0.2
            curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
            sudo apt-get -y install nodejs=14.17.0-1nodesource1

            npm install --global yarn

            yarn production:prep:install
            yarn install
            yarn production
          host: ${{ env.SERVER_IP }}
          user: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
